import { GalleryItem } from "@/types";

export const galleryItems: GalleryItem[] = [
  {
    id: 1,
    category: "Builds",
    title: "Dark Gothic Castle",
    description: "An imposing dark fortress rising into the night sky",
    src: "/gallery/dark-castle.png",
    alt: "Dark Gothic Castle",
    featured: true,
  },
  {
    id: 2,
    category: "PvP",
    title: "Zozo's Grave",
    description: "The resting place of zozo after a battle",
    src: "/gallery/crate-opening.png",
    alt: "Zozo's Grave",
    featured: false,
  },
  {
    id: 3,
    category: "PvP",
    title: "Zozo vs Oz_black0",
    description: "An intense fight between zozo and oz",
    src: "/gallery/players-at-base.png",
    alt: "Zozo vs Oz_black0",
    featured: false,
  },
  {
    id: 4,
    category: "Community",
    title: "Admin Shenanigans",
    description: "Even the admins know how to have a little fun",
    src: "/gallery/admin-and-player.png",
    alt: "Admin Shenanigans",
    featured: false,
  },
  {
    id: 5,
    category: "Community",
    title: "Village Explorers",
    description: "Friends meeting up in a local village settlement",
    src: "/gallery/friends-in-village.png",
    alt: "Village Explorers",
    featured: false,
  },
  {
    id: 6,
    category: "Builds",
    title: "Fortress Courtyard",
    description: "The glowing purple beacons inside the dark fortress",
    src: "/gallery/dark-fortress-courtyard.png",
    alt: "Fortress Courtyard",
    featured: false,
  },
  {
    id: 7,
    category: "Builds",
    title: "Fortress Portals",
    description: "Mysterious portal area surrounding the castle",
    src: "/gallery/dark-fortress-portals.png",
    alt: "Fortress Portals",
    featured: true,
  },
  {
    id: 8,
    category: "Builds",
    title: "Dark Fortress Gates",
    description: "The grand entrance to the gothic fortress",
    src: "/gallery/dark-fortress-entrance.png",
    alt: "Dark Fortress Gates",
    featured: false,
  },
  {
    id: 9,
    category: "Events",
    title: "Season 1 Champions",
    description: "Honoring the legendary players of Season 1",
    src: "/gallery/season-1-champions.png",
    alt: "Season 1 Champions",
    featured: true,
  },
  {
    id: 10,
    category: "Builds",
    title: "Crate Area",
    description: "The mystical crate area with rare rewards",
    src: "/gallery/crate-area.png",
    alt: "Crate Area",
    featured: false,
  },
  {
    id: 11,
    category: "Builds",
    title: "Fortress Crate Room",
    description: "Loot crates displayed before the grand fortress",
    src: "/gallery/fortress-crates.png",
    alt: "Fortress Crate Room",
    featured: false,
  },
  {
    id: 12,
    category: "Builds",
    title: "Server Lobby",
    description: "The beautiful main hub of MeerMC",
    src: "/gallery/MeerMC_Lobby.png",
    alt: "Server Lobby",
    featured: true,
  },
  {
    id: 13,
    category: "PvP",
    title: "PvP Arena",
    description: "Where legends are made and battles are fought",
    src: "/gallery/pvp-arena.png",
    alt: "PvP Arena",
    featured: false,
  },
  {
    id: 14,
    category: "Builds",
    title: "Community Spawn",
    description: "A welcoming start for all new players",
    src: "/gallery/spawn.png",
    alt: "Community Spawn",
    featured: false,
  },
  {
    id: 15,
    category: "Community",
    title: "Spawn Hangout",
    description: "Admin and Investor chilling at spawn",
    src: "/gallery/admin-and-investor-spawn.png",
    alt: "Spawn Hangout",
    featured: false,
  },
  {
    id: 16,
    category: "Builds",
    title: "Inside the Dark Fortress",
    description: "Exploring the inner halls of the dark fortress",
    src: "/gallery/inside-dark-fortress.png",
    alt: "Inside the Dark Fortress",
    featured: false,
  },
  {
    id: 17,
    category: "Community",
    title: "Portals Exploration",
    description: "Exploring the mysterious portals together",
    src: "/gallery/admin-and-investor-portals.png",
    alt: "Portals Exploration",
    featured: false,
  },
  {
    id: 18,
    category: "Community",
    title: "Fortress Expedition",
    description: "Meeting up at the entrance of the dark fortress",
    src: "/gallery/admin-and-investor-entrance.png",
    alt: "Fortress Expedition",
    featured: false,
  }
];
